apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: demo-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB01A6WNQwE4eipU3xqcZIuj2GpwS9Mgz+T3inplA+EsNQQGKKu+GNmXqLmrWzyMrVryw0zfaxa9+rpWxocBEcCPAYEEm3RMKZxH/HJqxPGuFVzVyQIdznqq4gd5ZwdMTIB7lizEzLr61yoIs5s2zeC68UP6O6k//vrkBI05GQAP7Bm7yyqHv4Chy/wP6lC5vTq0xiau9bNtPrANJW7BnJ44ieGxq0hsLwoCLn6yic9gMWrNeEbl0MkMo6JC63pxmZGl3/vJw83Pzp4pfA6Vv5Dx6BfOYU/UDD41DI4XDxTxUrG+Bq/eUGZHj9/BZ3o/wUy/nPnwxYz3sSs9xuKNDAWZcGJ9HxHq1Stu0AjKyLfdaf3AzC+UfQF64CJu5TXYTPsDSm3qVPB98+aPRVbbZ+wv11Jj0F6iVHu+wHdZhzuVVdv/Gj0i3woa97rLR8Tb4Q7kYY/PMM0/gKHnbe3MTcrNPx5wSscyqzY+F/3J316QTn5HX7I4725gO8RjqOPfmvNR8vfyaDp9uZDzaArCB/bJPsNlLA5dsOv6WUPeo/YeuZtya4u/HOgef0Wzt5bz5A2rxreCDkeWjzgWLYoMdBEyH8HAoXD2h/kAyrrHyXi3et0dfLo8CA8B/Q+jh8qK5/QFYsJW0cwU2cexDHXsNu9rBXzrUhCMHlOYDMzikL88I8PoZ6tkEInFt3cZefqpdmQSYx39MAmKMY7Z0UZpJh+9IBNevMFsJExv9fdQh8SytNdYwtqlxScdhASmtDBWxqnY2kF8yytWCAtSqXw99F7XJd420GGaVYRztnMgEKfz9yjKGlB1CkA9pkG2QNgSM2Ks49dWr0/WbQI7CQgJIyzZdp6sI9tuy8ob11aamFfqw2NRIiyEhYiIRpbjkqF69IQ45sC5qU/QZrrZc0tMMNKn9nmxoVRdcam8XZDbfufAVVyYPQCWKZTMLxZ
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: demo-cicd
    type: kubernetes.io/dockerconfigjson
status: {}
