apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-prod-rdisc-cli
  namespace: demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgArqn3yyPoyCg+nJZrozFdr4k30pMuxiHs5FyV2+MU0t71hgD4v4kg7DaalIAsoyhAi6vTyWPp3o8fxzv7/1cJaHWC7vNG6k9Y0NZgOOU73WATrib7NKKPzwD9T5M9NXXf6JR2dWC6E8Kp/xUJtr/ZdSw+/jXL0fBlK+qB2sTb8YgJLOnwUu2KVP3kkPhrFSFzL1BK0TAMYXlJ7zaiT1z4w3cSCDwpwSZj+oeb/D4kUzpyUChb0GJBNowsKON/O5e/crjNefT6Z+9ATBKdEd7DnRnMiNQdNTHaRbV04NyZsbVodSdjX2AmY6n3P+Bovg7Ln6WLvHwhwda4OFe+0GsYNqWGK+1f3FVWsBu6Wt+4lkobZ03IEVnW8/NYHd+Lwh6Wl9TWTvg2IPXc591wG9ZlEhEmAz6iObXZ/VvM+3iIzMKx7b5/ASuF8w6SOi68pLVCOhrOTd3eDqcCjJo+ooo06ilKGn8ezoetWEzno7HG+2Szyd3V4qkUcgeZLcKh9xuYKpYmX/dMyZLJG0PY2lOCZA9A5ID6dbYno4Ff+ez89dA/dKJg8qv+K4PGRoTSZYY50To+D6AAhYS/3U+7TOxKRWpOXhqlRIaQCpeqpOmyJ5hVpA7Ldd+GXAvwkbKqzafQfGRHcZgp2sz7SbayqK6Aqcqe8Lv6oSCp/xbz5GEuYdIvhaZrI4hI88u44sns4NH8=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-prod-rdisc-cli
      namespace: demo-cicd
    type: Opaque
status: {}
