apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: demo-cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/gitops166')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      name: ci-dryrun-from-push-template
  - bindings:
    - name: demo-dev-app-taxi-taxi-binding
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-demo-dev-taxi
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/taxi')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-taxi
    template:
      name: app-ci-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-demo-stage-bus
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/bus')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-bus
    template:
      name: app-ci-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-demo-stage-bus1
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/bus1')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-bus1
    template:
      name: app-ci-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-demo-stage-truck
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/truck')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-truck
    template:
      name: app-ci-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-demo-stage-truck-frontend
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/truck-frontend')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-truck-frontend
    template:
      name: app-ci-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-prod-car
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/car')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-car
    template:
      name: app-ci-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: demo-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-prod-cycle
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/cycle')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-cycle
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
