apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgDCUrhtEjrcFEfmHMEfCcuXifB9huMRbPyImyqQt7WT1ggK4EQ2Xi+2g92kJ2AzBid4dm0R68fm0f5SyQOYUCa+OwoFVAeI1E3fKmebGeu+RetWAs/40uGE2E+1r/5vNf15Qga/6p7/oY4s0OXkQ+KOe985aXDjC50Pp+3huFCM4E0X7mfErkTZM/U4bWfXltrly34vrX07jcuHerxlkogzDovUmug2OIX7QSVx9m0KD43640PumZ4vb9U6PkxjyA8cpp2tDwyHcBLEC5naSKdXubTgZl0Mpmc8n+jz4eezOzFex77gCt4v1DyBYe4hSxvbifj0zaS8C4mhLgQU94lT2Bnz5m8eK/PnjpTBACoRYuG1Nqyr9EfNPFh3JDczIN4kR0aIJKALotGuxTrluefjkPJDt8lEef0+IA0S1JZxRy/d5doYnfb/Qn5z3Pv3UYOZbggo8ehyihsgsj/uuHOZ/FSqK8bDsuhgs0qAqgmz64zWF9unuJ/l06ctUpIP+7Cge3tbHIZTEq7OgbgInEcFtRNXMuU7Db87JziSdCqCodQd8PaCGicGWM9QniML/PZJmfzNPC/LtjPVRmO1yRYrqv+Ij1viMhs76gDhLkR+g/2R7qjKk2xRH7miB8wHnd2KeHPePJU3n2DnDDsCHekR31yEmLR+CGRc53rTwHf+apX8PKDK3E5SfR5h+MWE0M+Eo6AKWLp6rnkQ++K5efXq9wXPCMC+w7mni7MZRtLwg8LsBgb0St8VzPigSOsYvL4E46wQAhMR8f4LxhtD4OHeeUeeHlCEnYGcUT6L4luwWCruRPEYtrp3p/sSYE1trf6byQTfT0rV3Rt4y3qBkX6s3IiNZr09kct44vFI2/bXGYXmPSpKJQIiXJ7Ven/Ox3iuRf/DDwbGoa+uSgWg+bjeDQI9A+hGkbm6ySV5U2r7zZJ4bR0RRCY712Liw/mFdMD+3zMPhAV2uHpgGedIkTJ3Ukdv2oRsTQ27WM8k1ELeGeMos5pY62YyM1aVSvAG9Vqhrg5O+zlxo0+nCCx1yq1WGP+vab6lE/O/lgpKMAlStn0TsghzTizaKXSgdIQjftLT9y8efrxbd2llStBhA3WU/TajysfQYKbPK1aF9NNWbX+Dve/rhCERuzAums7YLihBBE1mHd9DrbQukJ+E9KYOU3Stu8ecR2s9IzBC4fqv4YWZltv6dnv67OH9KTaQYnHE0LNLrk0B2Qw/Ir+5XazxR0Tv8MQPN9TIOJDHal5rJyhpnjgxSDk3X6yAgO2ZsvG+RMBB+uofWA1UcXbL8ZsbVtF+yS/ae5EHgThpYUofxTGPzmxJhpIYndGzab80qYyZ1h4hfCU/vQdOeWKyTikS4vUDJsC9o/j3JQuKpwFhjZzBJ3I=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
