apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBlfvr7WH2YliBRh8JfyYsCA27pwwf6N3bKUPRuy+eiMXIOfgUskd3ZjFhUWbi3oUDns/doQzRoC2Bjnt1VqLsCYmErgzB3FgMZThZ6/IWW1JXWCZ5BS61lOmEQJZSc7SsfRpM7jnttcCqcmvgCZks2mGkc9rJhdDnJNsZQbHnws/uautKi+KNVqeMHYEsHvWZgnGX1gCA/GKAU/m9buq/FJpJ1MoN2nOwN7otydMpilvjSjRyFqQMtS5X2Nq68E57z2Dfw09sez/Hlpqc4PP+1fkeG9XDEQUQmW8Nz7j9E2NdX49IcI0+gAyBGxzFx84ud93beel6ezURVQJPPH+dDtUibAGGmBSmrt5b4I3WdOk7Ggq82GvoLcNakKKMnGHQ1BMWvKjadDAjjJs9H82EsGj4NWO1Jt8zQr8Rt9nfoU524p842WExOIGCN12lI3dCtYDmkrl2hRp4DX8eTtdTOrUOkdEnxVkGIL3dGOctxpJqK2XZepYAQYM9/DkmvutNuZofTaigF/UWu7ubWOK7aRWC+skJdtJ6vQWU804ursACXdA/ebXoVFHBymzGXFD3DdwMBUENMqlAErCyx30ioflkvr5sH6GZGaAg2FAMp3K9uuFePAQ+FQ4xalGU0qeH/NIR+yVisF0OjqZwIr6rrr/aEgWSRjTpz5fP0AqDuzrFw3o+UovSrVAjgtZST1yfPLCHwQvt97vWnxzv9INSBo4LFfw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
