apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBaBoUZVwxCGzFxRN/OpYy4TzoRn5vGtzdKNdDlyfyp8q89m8nSOA8GxNg3I9TDlyVOrS3Mej2sr8aLKAfuBcTRLTdNOyVsQ459MIhXUwkB7mlHlAkVx8VREkd1zNG8MrEYSx7XB1tSIV8Cmj2GQypXT1nYGR+RvjleDzTBrZP/bCNVo5vsD+1r1pSwieFaek0GMluGP3pRDZT4bHxcKKfshmaPh70srdZECH9k+so/q6i22W89Jt6rvj/H4zdIoTzrR+OjIF1/ACMt/R7cBR3TG003NamgXyVolkDZz6+cBT9DFvwoAylFD5z7GQKS4qywKV4DuuvzF+abEeIFcJIoymjyFkG/ESegLVKO0N3uZ2o6+Wg3fqvDRVfVT/t95min/WXIRhTTXZ5L086yfamDxd/NX8DEy+0SFgDzyTQm5xZvWfAJqCj2nHbAHmVJbx3Lq49fax2+czAKkFV+EbCLnIPtxT4nsmKWPuLMU5bGmLOkBmgGCqOp7+0Ux6Los9uTuZU/OMpkLit4teYkCMiND91VvUam0Jmag8zicYITWxdQMjNZ80b8Qx1VDv9ngG8Zxwp163QdA/stNbLDTOhytAx7drUEtG+H2kbHJOmiefSIo3uZhZDgyt4B0/0/3lsar5gjh7XWxLG9WKS5okGZhbaer8J6+JIebgg69O9RoxsGv1P/OFrHzkMFPNCiuSNAZLx0XJ4jyWTNe01xQ+T/eDHoBQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
