apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: redis-cli
    app.kubernetes.io/part-of: bus-app
  name: redis-cli
  namespace: prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: redis-cli
    app.kubernetes.io/part-of: bus-app
status:
  loadBalancer: {}
